# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allow&PublicKeyRetrieval=true
    username: root
    password: 12345678
  elasticsearch:
    username: elastic
    password: 123456
    uris: http://localhost:9200
  rabbitmq:
    username: guest
    password: guest
    host: 127.0.0.1
    port: 5672
  data:
    redis:
      port: 6379
      password: 123456
      host: 127.0.0.1

blog:
  upload-path: /users/mingchiuli/desktop/
  add-resource-locations: file:/users/mingchiuli/desktop/
  jwt:
    secret: ti8n3439n439t43ld9nv9343ddfer09hti8n3439n439t43ld9nv9343ddfer09ti8n3439n439t43ld9nv9343ddfer09fti8n3439n439t43ld9nv9343ddfer09f
    #    七天
    expire: 604800
    header: Authorization



